[profile.default]
src = "src"
out = "out"
load_from_env_file = true
libs = ["lib"]
solc_version = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip/',
    '@chainlink/contracts/=node_modules/@chainlink/contracts/',
    'forge-std/=lib/forge-std/src/',
]

# Add file permissions for JSON config reading
fs_permissions = [
    { access = "read", path = "../ccip-faucet-fe/public/configs" },
    { access = "read", path = "./configs" }
]


